### ISSUE TITLE
CommandTimeout cannot be found

### ISSUE THREAD

**Issue by structre40** [GustavoAmerico/SQLServerDeploy#3]
I am trying to use this extension but I get the following error:
 ##[error]System.Management.Automation.RuntimeException: The property 'CommandTimeout' cannot be found on this object. Verify that the property exists and can be set.
2018-06-07T15:50:57.8800298Z    at CallSite.Target(Closure , CallSite , Object , Int32 )
2018-06-07T15:50:57.8800773Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2018-06-07T15:50:57.8801110Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2018-06-07T15:50:57.8801421Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

Any ideas?

**Comment by GustavoAmerico** [comment]
What's SQL Server Data Tools version installed your agent server?

**Comment by GustavoAmerico** [comment]
#4
